### ISSUE TITLE
TypeErrors for conditional functions....

### ISSUE THREAD

**Issue by jp1444** [learn-co-curriculum/function-arguments-readme#1]
I'm getting TypeErrors for the 'writing functions with conditionals'. Is this supposed to happen?

**Comment by mas16** [comment]
Hi jp1444, thanks for posting! The function arguments readme has purposeful TypeErrors to illustrate how to use variables in functions but no section called 'writing functions with conditionals.' The section 'writing functions with conditionals' in the Conditionals Python Lab should not have TypeErrors. If you get stuck, you can use the Ask A Question Feature in Learn to get assistance or consult the solution branch on GitHub. Hope that helps!
